<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClientesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $jsonString = '[
                {"codigo":"000","nombre_compl":"Sergio Maia","apodo":"Sergio Maia"},
                {"codigo":"001","nombre_compl":"Luciano Nichetti","apodo":"Luciano"},
                {"codigo":"002","nombre_compl":"Martín Selva","apodo":"Martín"},
                {"codigo":"003","nombre_compl":"Daniel","apodo":"Daniel Máquinas"},
                {"codigo":"004","nombre_compl":"Mario Vernazza","apodo":"Mario Vernazza"},
                {"codigo":"005","nombre_compl":"Flávio Gomes","apodo":"Flávio"},
                {"codigo":"006","nombre_compl":"Amilcar Veneziani Dias Junior","apodo":"Amilcar"},
                {"codigo":"007","nombre_compl":"Jonathan Luiz Gardini","apodo":"Xiru"},
                {"codigo":"008","nombre_compl":"Deivis","apodo":"Deivis"},
                {"codigo":"009","nombre_compl":"Renan","apodo":"Renan Piaui"},
                {"codigo":"010","nombre_compl":"Caio MF Automotivos","apodo":"MF Auto"},
                {"codigo":"011","nombre_compl":"Bassan Safadi","apodo":"Bassan"},
                {"codigo":"012","nombre_compl":"Mohamed ","apodo":"Mudi"},
                {"codigo":"013","nombre_compl":"Mohamed Zabian ","apodo":"Med Londrina"},
                {"codigo":"014","nombre_compl":"Antonella Saez","apodo":"Anto"},
                {"codigo":"015","nombre_compl":"Gustavo Vincentin","apodo":"Gustavo Vincentin"},
                {"codigo":"016","nombre_compl":"Thiago Jose Italo Ribeiro","apodo":"Thiago Italo "},
                {"codigo":"017","nombre_compl":"Débora Villares","apodo":"Débora"},
                {"codigo":"018","nombre_compl":"Antero","apodo":"Antero"},
                {"codigo":"019","nombre_compl":"Reginaldo Rocha Loures","apodo":"Nardinho"},
                {"codigo":"020","nombre_compl":"Michel","apodo":"Michel"},
                {"codigo":"021","nombre_compl":"Alberto Tiziano Dal Ben","apodo":"Alberto Tiziano"},
                {"codigo":"022","nombre_compl":"Carlos A Junior","apodo":"Carlos Junior"},
                {"codigo":"023","nombre_compl":"Eduardo","apodo":"Eduardo Foz"},
                {"codigo":"024","nombre_compl":"Vinicius Andrade Matos","apodo":"Vinicius Matos"},
                {"codigo":"025","nombre_compl":"Ibrahim Hijazi","apodo":"Ibra"},
                {"codigo":"026","nombre_compl":"Marcos","apodo":"PACO"},
                {"codigo":"027","nombre_compl":"Luiz Santos","apodo":"Luiz Santos"},
                {"codigo":"028","nombre_compl":"Mauro","apodo":"Mauro Minas"},
                {"codigo":"029","nombre_compl":"Enrico","apodo":"Enrico"},
                {"codigo":"030","nombre_compl":"Eduardo Deitos","apodo":"Deitos"},
                {"codigo":"031 ","nombre_compl":"Hugo Tsukuda","apodo":"Hugo Maringá"},
                {"codigo":"032","nombre_compl":"Rodrigo","apodo":"Rodrigo MM"},
                {"codigo":"033","nombre_compl":"Rhuann Weber ","apodo":"Rhuann Weber"},
                {"codigo":"034","nombre_compl":"Gleison","apodo":"Gleison"},
                {"codigo":"035","nombre_compl":"Thiago Lemos","apodo":"Thiago Lemos"},
                {"codigo":"036","nombre_compl":"Júnio Zezinho","apodo":"Zezinho Sanfona"},
                {"codigo":"037","nombre_compl":"Tonello","apodo":"Tonello"},
                {"codigo":"038","nombre_compl":"Rafael Zoschke","apodo":"Rafael Zoschke"},
                {"codigo":"039","nombre_compl":"Felipe Nascimento","apodo":"Felipe Nascimento"},
                {"codigo":"040","nombre_compl":"Giuliano Agnelli","apodo":"Giuliano Agnelli"},
                {"codigo":"041","nombre_compl":"Evandro Oliveira","apodo":"Evandro"},
                {"codigo":"042","nombre_compl":"Felipe Augusto de Cordova","apodo":"Felipe Cordova"},
                {"codigo":"043","nombre_compl":"Everson Mesquita","apodo":"Mesquita"},
                {"codigo":"044","nombre_compl":"Luiz Fernando","apodo":"Luiz Fernando"},
                {"codigo":"045","nombre_compl":"Rafael Stadler","apodo":"Rafael Stadler"},
                {"codigo":"046","nombre_compl":"Alex (AB)","apodo":"Alex (AB)"},
                {"codigo":"047","nombre_compl":"Frederico Frazão","apodo":"Fred"},
                {"codigo":"048","nombre_compl":"Evaldo Marechal","apodo":"Marechal"},
                {"codigo":"049","nombre_compl":"Injediesel","apodo":"Elias Injediesel"},
                {"codigo":"050","nombre_compl":"Oswaldo Loureda","apodo":"Professor Oswaldo"},
                {"codigo":"051","nombre_compl":"Marlos Dal Igna","apodo":"Marlos Gol GTI"},
                {"codigo":"052","nombre_compl":"Bob Cliente","apodo":"Bob Cliente"},
                {"codigo":"053","nombre_compl":"Marcelo Martellini","apodo":"Martellini"},
                {"codigo":"054","nombre_compl":"Jevan","apodo":"Jevan"},
                {"codigo":"055","nombre_compl":"Mauro Oliveira","apodo":"Mauro EUA"},
                {"codigo":"056","nombre_compl":"Diego Belletini","apodo":"Diego Belletini"},
                {"codigo":"DS","nombre_compl":"Junior ","apodo":"Junior DS Performance"},
                {"codigo":"057","nombre_compl":"Nilson Rode","apodo":"Nilson Rode"},
                {"codigo":"058","nombre_compl":"Marcelo Martellini","apodo":"Marcelo Martellini"},
                {"codigo":"059","nombre_compl":"Injepro (Guinho)","apodo":"Guinho Injepro"},
                {"codigo":"060","nombre_compl":"Jeferson Junior","apodo":"Jeferson (Elias Injediesel)"},
                {"codigo":"061","nombre_compl":"Guilherme Viecelli","apodo":"Guilherme Viecelli"},
                {"codigo":"062","nombre_compl":"Ailton Ferreira Júnior","apodo":"Ailton Ferreira"},
                {"codigo":"063","nombre_compl":"Fabio Marinho","apodo":"Fabio"},
                {"codigo":"064","nombre_compl":"Valmor José Gazoni Júnior","apodo":"Valmor"},
                {"codigo":"065","nombre_compl":"Mauro Antonio Schnaider","apodo":"Mauro Schnaider"},
                {"codigo":"066","nombre_compl":"Cleberson José Giacchini","apodo":"Cleberson "},
                {"codigo":"067","nombre_compl":"Anderson Santana","apodo":"Anderson Santana"},
                {"codigo":"068","nombre_compl":"Roberto Vieira Moreno","apodo":"Beto"},
                {"codigo":"069","nombre_compl":"Roberto Cici","apodo":"Roberto Cici"},
                {"codigo":"HB","nombre_compl":"Heraldo Bueno","apodo":"Heraldo"},
                {"codigo":"070","nombre_compl":"André Barbosa Barroca","apodo":"André Maringá"},
                {"codigo":"071","nombre_compl":"Mário Augusto Grotta Moletta","apodo":"Mário Moletta"},
                {"codigo":"072","nombre_compl":"Ricardo Barretto Toledo","apodo":"Ricardo Barretto "},
                {"codigo":"073","nombre_compl":"Warley Leonello","apodo":"Warley"},
                {"codigo":"074","nombre_compl":"Marcelo Toss","apodo":"Marcelo Toss"},
                {"codigo":"075","nombre_compl":"Elias Injediesel","apodo":"Elias Injediesel Pessoal"},
                {"codigo":"076","nombre_compl":"Cesar Moura Epiphanio","apodo":"Cesar Epiphanio"},
                {"codigo":"077","nombre_compl":"Marcos Bot Ribeiro","apodo":"Marcos Ribeiro"},
                {"codigo":"078","nombre_compl":"André Augusto Gil de Oliveira","apodo":"André Augusto"},
                {"codigo":"079","nombre_compl":"João Zaions","apodo":"João Zaions"},
                {"codigo":"080","nombre_compl":"Anderson Batista Signor","apodo":"Dinho Ferro Velho"},
                {"codigo":"081","nombre_compl":"Rogelio Luiz Faoro","apodo":"Rogelio Faoro"},
                {"codigo":"082","nombre_compl":"Altemir Dupond","apodo":"Altemir Pinhalzinho"},
                {"codigo":"083","nombre_compl":"Gustavo Chaves Lopes","apodo":"Gustavo Lopes"},
                {"codigo":"084","nombre_compl":"Valter Bomtempo Junior","apodo":"Valter (Valmor)"},
                {"codigo":"085","nombre_compl":"Eduardo Klygis","apodo":"Eduardo Klygis"},
                {"codigo":"086","nombre_compl":"Francisco Machado Batista Lage","apodo":"Shico Batista"},
                {"codigo":"087","nombre_compl":"Julio Miqueo","apodo":"Don Junio ExporUSA"},
                {"codigo":"089","nombre_compl":"Albino Signorelli","apodo":"Bino"},
                {"codigo":"090","nombre_compl":"Marco Antônio da Silva","apodo":"Marco Antônio"},
                {"codigo":"091","nombre_compl":"Auto Hauss S.A.","apodo":"Ferrari Autohaus"},
                {"codigo":"092","nombre_compl":"TNA AutoHauss","apodo":"TNA AutoHauss"},
                {"codigo":"093","nombre_compl":"Azor Silvio Corona Filho","apodo":"Azor Filho"},
                {"codigo":"094","nombre_compl":"Alan Fontes","apodo":"Alan Fontes"},
                {"codigo":"095","nombre_compl":"José Francisco dos Santos Junior","apodo":"José Francisco Racetech"},
                {"codigo":"096","nombre_compl":"Roberto Hurtado Silva","apodo":"Roberto Hurtado"},
                {"codigo":"097","nombre_compl":"Noel Paniza Sanches Garcia","apodo":"Noel Paniza"},
                {"codigo":"098","nombre_compl":"Diego Assalin de Carvalho","apodo":"Diego Assalin"},
                {"codigo":"099","nombre_compl":"Fernando Henrique","apodo":"Fernando Henrique"},
                {"codigo":"100","nombre_compl":"Alessandro Francisco dos Santos","apodo":"Alessandro Bicudo"},
                {"codigo":"101","nombre_compl":"Flávio Haltech","apodo":"Flávio Haltech"},
                {"codigo":"102","nombre_compl":"Fernando Stella","apodo":"Fernando Stella"},
                {"codigo":"103","nombre_compl":"Thiago Tanahara","apodo":"Thiago Tanahara"},
                {"codigo":"104","nombre_compl":"Gustavo Kava","apodo":"Gustavo Kava"},
                {"codigo":"105","nombre_compl":"Vitor Leal Filizzola Filho","apodo":"Vitor Filizzola"},
                {"codigo":"106","nombre_compl":"Jeferson Sergio Medvid","apodo":"Jeferson Jecão"},
                {"codigo":"107","nombre_compl":"Jorge Luis Iglesias Villalobos","apodo":"Jorge Subaru Performance"},
                {"codigo":"108","nombre_compl":"Diego Leituga Elias","apodo":"Diego Leituga"},
                {"codigo":"109","nombre_compl":"Patrick Nardi AutoHauss","apodo":"Patrick AutoHauss"},
                {"codigo":"110","nombre_compl":"Patrick Cassab","apodo":"Patrick Cassab"},
                {"codigo":"111","nombre_compl":"Israel Assis de Oliveira","apodo":"Israel Oliveira"},
                {"codigo":"112","nombre_compl":"Valdir Scremin","apodo":"Valdir Jetski"},
                {"codigo":"113","nombre_compl":"AutoHauss RC","apodo":"RC AutoHauss"},
                {"codigo":"114","nombre_compl":"Murilo Gonçalves Pereira","apodo":"Murilo Gonçalves"},
                {"codigo":"115","nombre_compl":"Chacal Autohauss","apodo":"Chacal Autohauss"},
                {"codigo":"116","nombre_compl":"Daniel Eusébio Vázquez Alarcón","apodo":"Daniel Arquiteto"},
                {"codigo":"117","nombre_compl":"Julio Saez","apodo":"Julio Saez"},
                {"codigo":"118","nombre_compl":"João Guilherme Saragoza de Oliveira","apodo":"João Saragoza"},
                {"codigo":"119","nombre_compl":"David Aguilar","apodo":"David Aguilar Primo Chesca"},
                {"codigo":"120","nombre_compl":"Rodrigo Augusto Silva Ferreira","apodo":"Rodrigo Ferreira"},
                {"codigo":"121","nombre_compl":"Thomas Henrique Hussein Jomaa","apodo":"Thomas Jomma"},
                {"codigo":"122","nombre_compl":"Reinaldo Bellis","apodo":"Reinaldo Costela"},
                {"codigo":"123","nombre_compl":"Luis Bello Pereira","apodo":"Luis Repuestos"},
                {"codigo":"124","nombre_compl":"Marcelo Assunção Peixoto","apodo":"Marcelo Peixoto"},
                {"codigo":"125","nombre_compl":"Derlys","apodo":"Derlys Tío Chesca"},
                {"codigo":"126","nombre_compl":"Gabriel Marcelo Lezcano Alcaraz","apodo":"Gabriel Lezcano Autohaus"},
                {"codigo":"127","nombre_compl":"Leandro Bortolato","apodo":"Leandro Cambio"},
                {"codigo":"128","nombre_compl":"Christiano José Júlio","apodo":"Chris Los Hermanos"},
                {"codigo":"129","nombre_compl":"Diego Quitério","apodo":"Diego Irmão Júnior Rapidos"},
                {"codigo":"130","nombre_compl":"Marcelo Moraes de Brito","apodo":"Marcelo Brito"},
                {"codigo":"131","nombre_compl":"Marcelo Steinle Riello","apodo":"Marcelo Toretto"},
                {"codigo":"132","nombre_compl":"Thomas Edson de Pauli","apodo":"Thomas DePauli"},
                {"codigo":"133","nombre_compl":"Jeferson Alemão","apodo":"Jeferson Alemão"},
                {"codigo":"134","nombre_compl":"Alexandre Vasconcelos","apodo":"Alexandre Vasconcelos"},
                {"codigo":"135","nombre_compl":"Guilherme Volpini","apodo":"Guilherme Volpini"},
                {"codigo":"136","nombre_compl":"Jesus Iglesias Villalobos","apodo":"Jesus Subaru Performance"},
                {"codigo":"138","nombre_compl":"Renato Lemos Santiago","apodo":"Renato EUA"},
                {"codigo":"139","nombre_compl":"Neimar Luís Sgorla","apodo":"Neimar Sgorla"},
                {"codigo":"137","nombre_compl":"Cristiano Garcia","apodo":"Cristiano Indutech"},
                {"codigo":"140","nombre_compl":"Alvaro Dias","apodo":"Alvaro Dias"},
                {"codigo":"141","nombre_compl":"Francisco Machado Batista Lage","apodo":"Shico Batista"},
                {"codigo":"142","nombre_compl":"Neto","apodo":"Neto"},
                {"codigo":"143","nombre_compl":"Christiano Pinheiro","apodo":"Christiano"},
                {"codigo":"144","nombre_compl":" Fabiano Carvalho Leopoldo","apodo":"Fabiano Rife"},
                {"codigo":"145","nombre_compl":"Robson de Oliveira ","apodo":"Robson BMW"},
                {"codigo":"146","nombre_compl":"Rafael Antonio de Castillos","apodo":"Rafael Castillos"},
                {"codigo":"147","nombre_compl":"Sousa Llantas","apodo":"Sousa Llantas"},
                {"codigo":"148","nombre_compl":"Michael Piffer","apodo":"Michael Piffer"},
                {"codigo":"149","nombre_compl":"Levi Pereira Alves","apodo":"Levi Pereira Alves"},
                {"codigo":"088","nombre_compl":"Ricardo Peruso Lira","apodo":"Ricardo Chato"},
                {"codigo":"150","nombre_compl":"Luis Portillo","apodo":"Portillo"},
                {"codigo":"151","nombre_compl":"Jefferson Rodrigues Manoel","apodo":"Manoel"},
                {"codigo":"152","nombre_compl":"Eduardo Resende Araujo","apodo":"Eduardo Araujo"},
                {"codigo":"153","nombre_compl":"Milton Brollo","apodo":"Milton (Patrik)"},
                {"codigo":"154","nombre_compl":"Albert Bernardes","apodo":"Qualicar Albert"},
                {"codigo":"155","nombre_compl":"Nivaldo Hilbert","apodo":"Nivaldo (Valdir)"},
                {"codigo":"156","nombre_compl":"Thiago Dreher Santos","apodo":"Thiago Dreher "},
                {"codigo":"157","nombre_compl":"Rodrigo Oliveira","apodo":"Rodrigo Oliveira"},
                {"codigo":"158","nombre_compl":"Marcelo","apodo":"Marcelo Vidriopar"},
                {"codigo":"159","nombre_compl":"Leandro Marques Ferreira","apodo":"Leandro Tururu"},
                {"codigo":"160","nombre_compl":"Kleber Rodrigues","apodo":"Kleber Rodrigues"},
                {"codigo":"161","nombre_compl":"Andre Nogueira Bueno","apodo":"Bueno Drift "},
                {"codigo":"162","nombre_compl":"Gilvan da Silva Paiva","apodo":"Peninha"},
                {"codigo":"163","nombre_compl":"Daniel Dias Gonçalves","apodo":"Daniel TT "},
                {"codigo":"164","nombre_compl":"Marco Tulio Arruda Helou","apodo":"Marco Tulio"},
                {"codigo":"165","nombre_compl":"Richard","apodo":"Richard Campusano"},
                {"codigo":"166","nombre_compl":"Luiz Fabio Silva Mendes","apodo":"Luiz Fabio"},
                {"codigo":"167","nombre_compl":"Daniel Santos","apodo":"Daniel Santos"},
                {"codigo":"168","nombre_compl":"Fabiano Pinto","apodo":"Fabiano Pinto"},
                {"codigo":"169","nombre_compl":"Agenor Bernardes da Silva","apodo":"Agenor"},
                {"codigo":"170","nombre_compl":"Igor Vinicius Fogagnoli Damaceno","apodo":"Igor Damaceno"},
                {"codigo":"VG","nombre_compl":"Victor Garcete","apodo":"Victor Garcete"},
                {"codigo":"171","nombre_compl":"Renato Schabatt Martins ","apodo":"Renato Martins"},
                {"codigo":"172","nombre_compl":"Sergio Roberto C Ganga","apodo":"Sergio Sapinho"},
                {"codigo":"173","nombre_compl":"Mohamed Zaiun","apodo":"Mohamed Zaiun"},
                {"codigo":"174","nombre_compl":"Carlos Zagallo","apodo":"Carlos Zagallo"},
                {"codigo":"175","nombre_compl":"Euclides Facchini Neto","apodo":"Euclides Facchini"},
                {"codigo":"176","nombre_compl":"Erick Henrique Medici","apodo":"Erick Medici"},
                {"codigo":"177","nombre_compl":"Renan Gambine Lima","apodo":"Renan Lima"},
                {"codigo":"178","nombre_compl":"Helyson Navas","apodo":"Helyson Navas"},
                {"codigo":"179","nombre_compl":"Nick Wurzel","apodo":"Nick Wurzel"},
                {"codigo":"180","nombre_compl":"Vilmar Fochesato","apodo":"Vilmar Fochesato"},
                {"codigo":"181","nombre_compl":"Rodrigo de Almeida Polasek","apodo":"Rodrigo Polasek"},
                {"codigo":"182","nombre_compl":"Alexandre Luiz Michelon","apodo":"Alexandre Michelon"},
                {"codigo":"183","nombre_compl":"Andre Luiz Marinho Fernandes Serrano","apodo":"André Marinho (Natal)"},
                {"codigo":"184","nombre_compl":"Marcelo Giacomazzi","apodo":"Marcelo Giacomazzi"},
                {"codigo":"185","nombre_compl":"Marcel Luciano Higuchi Viegas dos Santos","apodo":"Marcel Higuchi "},
                {"codigo":"186","nombre_compl":"Ricardo de Souza Mandalá","apodo":"Ricardo Mandalá"},
                {"codigo":"187","nombre_compl":"Eduardo Machado de Almeida","apodo":"Eduardo Almeida"},
                {"codigo":"188","nombre_compl":"Clayton Aparecido de Amurim","apodo":"Clayton Amurim (Caio)"},
                {"codigo":"189","nombre_compl":"Diego Ferreira Barcelos","apodo":"Diego Barcelos"},
                {"codigo":"190","nombre_compl":"Caio Augusto Silva","apodo":"Caio Silva"},
                {"codigo":"191","nombre_compl":"Jonas Regatieri de Oliveira","apodo":"Jonas Regatieri "},
                {"codigo":"192","nombre_compl":"Matheus Barudi Pauwels","apodo":"Matheus Barudi"},
                {"codigo":"193","nombre_compl":"Johrann Fritzen Nogueira","apodo":"Johrann Nogueira"},
                {"codigo":"194","nombre_compl":"Francis Junior Ferreira Maia","apodo":"Francis Maia"},
                {"codigo":"195","nombre_compl":"Anildo Rodríguez da Silva","apodo":"Anildo Rodríguez "},
                {"codigo":"196","nombre_compl":"Denes","apodo":"Denes Miami Bike"},
                {"codigo":"197","nombre_compl":"Renan Negrelli Ferreira","apodo":"Renan Ferreira"},
                {"codigo":"198","nombre_compl":"Daniel Stocchero Hatschbach","apodo":"Daniel Hatschbach"},
                {"codigo":"199","nombre_compl":"Eric Palazzi Coelho","apodo":"Eric Palazzi"},
                {"codigo":"200","nombre_compl":"Thaiana Oliveira da Silva","apodo":"Thaiana Oliveira "},
                {"codigo":"201","nombre_compl":"Marcelo Panades","apodo":"Marcelo Panades"},
                {"codigo":"202","nombre_compl":"Alael Nascimento Miranda Júnior","apodo":"Alael Nascimento "},
                {"codigo":"203","nombre_compl":"Felipe Baldussi","apodo":"Felipe Baldussi"},
                {"codigo":"204","nombre_compl":"Lucas Canevaroli Mantovani","apodo":"Lucas Mantovani"},
                {"codigo":"205","nombre_compl":"Lucas Rodrigues Henrique","apodo":"Lucas Prodrive"},
                {"codigo":"206","nombre_compl":"Phylipi Arthur Pardini Della Nina","apodo":"Phylipi Subaru"},
                {"codigo":"207","nombre_compl":"Franceli Dapieve Hahn","apodo":"Franceli Dapieve"},
                {"codigo":"208","nombre_compl":"Antonio César Ferreira","apodo":"César Ferreira"},
                {"codigo":"209","nombre_compl":"Giseli Denes","apodo":"Giseli Denes"},
                {"codigo":"210","nombre_compl":"Claudemir Isquerdo Melin","apodo":"Claudemir Melin"},
                {"codigo":"211","nombre_compl":"Marcio Goncalves Orofino","apodo":"Marcio Orofino"},
                {"codigo":"212","nombre_compl":"Thiago Verri Lopes","apodo":"Thiago Verri"},
                {"codigo":"213","nombre_compl":"George Cesar Barros Tani","apodo":"George Tani"},
                {"codigo":"ETL","nombre_compl":"ETL Don Ramón","apodo":"ETL Don Ramón"},
                {"codigo":"AAA","nombre_compl":"Triple AAA","apodo":"Triple AAA"},
                {"codigo":"214","nombre_compl":"Marcelo (Nene)","apodo":"Nene da Podium"},
                {"codigo":"MQ","nombre_compl":"Mario Quiñones","apodo":"Mario Quiñones"},
                {"codigo":"215","nombre_compl":"Cassio Lisandro Grossi","apodo":"Cassio Grossi"},
                {"codigo":"216","nombre_compl":"Givaldo Alves da Silva","apodo":"Givaldo Alves "},
                {"codigo":"217","nombre_compl":"Maiquel da Rosa Molinari","apodo":"Maiquel Molinari"},
                {"codigo":"218","nombre_compl":"Lucas Luiz Perlin","apodo":"Lucas Perlin"},
                {"codigo":"219","nombre_compl":"Lamonnyel Vieira de Moraes","apodo":"Lamonnyel Moraes"},
                {"codigo":"220","nombre_compl":"Bruno Lima Chaiben","apodo":"Bruno Lima"},
                {"codigo":"221","nombre_compl":"Rafael Severino de Oliveira","apodo":"Bila"},
                {"codigo":"222","nombre_compl":"Igor Eduardo Gonçalves","apodo":"Igor Gonçalves"},
                {"codigo":"223","nombre_compl":"Jackson Camargo da Conceição ","apodo":"Sandra (CGA)"},
                {"codigo":"224","nombre_compl":"Rogério dos Reis Silva","apodo":"Rogério Reis"},
                {"codigo":"225","nombre_compl":"Alael","apodo":"Alael"},
                {"codigo":"226","nombre_compl":"Gilberto Mendonça ","apodo":"Gilberto Mendonça "},
                {"codigo":"227","nombre_compl":"Bruno Gomes Gabriel","apodo":"Bruno Gomes "},
                {"codigo":"228","nombre_compl":"Lucas Chagas de Brito","apodo":"Lucas Chagas"},
                {"codigo":"229","nombre_compl":"Hector Mauricio Ferreyra","apodo":"Mauricio Ferreyra"},
                {"codigo":"230","nombre_compl":"Alexander Ceresa","apodo":"Alexander Ceresa"},
                {"codigo":"231","nombre_compl":"Daniel Netto Travizani","apodo":"Daniel Travizani"},
                {"codigo":"232","nombre_compl":"Alexandre","apodo":"Alexandre Evolution"},
                {"codigo":"233","nombre_compl":" Rafael Eduardo de Salvi del Buono","apodo":" Rafael Buono"},
                {"codigo":"234","nombre_compl":"Juan Andres Fontana Turnes","apodo":"Juan Fontana"},
                {"codigo":"235","nombre_compl":"Adriano Gonçalves","apodo":"Adriano Gonçalves"},
                {"codigo":"236","nombre_compl":"Leandro Cesar Cabral de Macedo","apodo":"Leandro Macedo"},
                {"codigo":"237","nombre_compl":"Mayckon Sergio Vicente","apodo":"Mayckon Vicente"},
                {"codigo":"238","nombre_compl":"Rodrigo Bueno de Moraes Milan","apodo":"Rodrigo Milan"},
                {"codigo":"239","nombre_compl":"Carlos Roberto Schoder Junior","apodo":"Junior Schoder"},
                {"codigo":"240","nombre_compl":"Consorcio Box","apodo":"Tanya Consorcio BOX"},
                {"codigo":"241","nombre_compl":"Wellington Lopes Cardoso","apodo":"Wellington Lopes "},
                {"codigo":"242","nombre_compl":"Paraguay Courrier","apodo":"Paraguay Courrier"},
                {"codigo":"243","nombre_compl":"Fabio Pegoraro","apodo":"Fabio Pegoraro"},
                {"codigo":"244","nombre_compl":"Wilmar Ribeiro de Freitas Júnior","apodo":"Wilmar Ribeiro"},
                {"codigo":"245","nombre_compl":"Lucas Silva Quintanilha","apodo":"Lucas Quintanilha"},
                {"codigo":"246","nombre_compl":" Luiz Carlos Villar Arias","apodo":" Luiz Carlos Villar "},
                {"codigo":"247","nombre_compl":"Clairton Luís Dillmann","apodo":"Clairton Dillmann"},
                {"codigo":"248","nombre_compl":"Daniel Neto Travizani","apodo":"Daniel FUNKO"},
                {"codigo":"249","nombre_compl":"Leandro Maffioletti Becker","apodo":"Leandro Becker"},
                {"codigo":"250","nombre_compl":"Germano Khun","apodo":"Germano"},
                {"codigo":"251","nombre_compl":"Thiago Alexandre Burger","apodo":"Thiago Burger"},
                {"codigo":"252","nombre_compl":"Alvaro Gotuzzo de Castro","apodo":"Alvaro Gotuzzo"},
                {"codigo":"253","nombre_compl":"Renato Araújo Macedo","apodo":"Renato Araújo "},
                {"codigo":"254","nombre_compl":"Carlos Augusto Jaze Janeta","apodo":"Carlos Janeta"},
                {"codigo":"255","nombre_compl":"Jhony Neu Dias","apodo":"Jhony Dias"},
                {"codigo":"256","nombre_compl":"Vinicius Pereira Neves","apodo":"Vinicius Neves"},
                {"codigo":"257","nombre_compl":"Lucas Dalsotto","apodo":"Lucas Dalsotto"},
                {"codigo":"258","nombre_compl":"Patrick Richard Cruz","apodo":"Patrick Cruz"},
                {"codigo":"259","nombre_compl":"Sergio Bergmann Souza ","apodo":"Sergio Bergmann"}
            ]';

        $clientes = json_decode($jsonString);

        foreach ($clientes as $cliente) {
            DB::table('clientes')->insert([
                'codigo' => $cliente->codigo,
                'nome' => $cliente->nombre_compl,
                'apelido' => $cliente->apodo,
                // Adicione outros campos conforme necessário
            ]);
        }
    }
}
